# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13d86b29eda518988426de560880ee24473338602fc205fc5c08ca82f8609c6fd3b4745512f7eb227698b0a9bbd83aa4955d07556f2c7d31ac68b108864b7723

test:
  secret_key_base: 410c9f557f77577e73c6e704b9772e2814114b9c03b78e8f35c5d74a3786a0aa90d2197429bcfd66ec156275830521b73e9feed0a1ded8afa3403cfa1be0ccdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
